version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: adoption-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adoption_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - adoption-network

  # Spring Boot Application
  adoption-app:
    image: sarah1407/adoption-project:latest
    container_name: adoption-springboot
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/adoption_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - adoption-network

  # SonarQube
  sonarqube:
    image: sonarqube:community
    container_name: adoption-sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    environment:
      - SONAR_LOG_LEVEL=INFO
    networks:
      - adoption-network

  # Prometheus
  prometheus:
    image: prom/prometheus
    container_name: adoption-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - adoption-network

  # Grafana
  grafana:
    image: grafana/grafana
    container_name: adoption-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - adoption-network

volumes:
  mysql_data:
  grafana_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:

networks:
  adoption-network:
    driver: bridge