version: '3.8'

services:

  mongodb:
    image: mongo:6.0
    container_name: adoption-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: adoption_db
    volumes:
      - mongo_data:/data/db
    networks:
      - adoption-network

  adoption-app:
    image: sarah1407/adoption-project:latest
    container_name: adoption-springboot
    depends_on:
      - mongodb
    ports:
      - "8089:8089"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/adoption_db
    networks:
      - adoption-network

volumes:
  mongo_data:

networks:
  adoption-network: