version: '3.8'

services:
  adoption-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adoptionProject
    ports:
      - "3306:3306"

  adoption-app:
    build: .
    ports:
      - "8089:8089"
    depends_on:
      - adoption-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://adoption-db:3306/adoptionProject?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"